version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
  mongo:
    image: mongo:5.0.3
    volumes:
      - ./data:/data/db
    restart: always
    ports:
      - "27017:27017"